version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: autos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "80:80"
    depends_on:
      - postgres
